"""admin kpis productos abonos clasificacion clientes

Revision ID: 021886d797e9
Revises: 81d5c35f33d2
Create Date: 2026-06-13 14:22:07.703456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '021886d797e9'
down_revision = '81d5c35f33d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('categoria', sa.String(length=40), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_abonos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('moneda', sa.String(length=5), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('referencia', sa.String(length=120), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['client_folders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client_folders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=30), nullable=False, server_default='prospecto'))
        batch_op.add_column(sa.Column('producto_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('valor_estimado', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('moneda_estimada', sa.String(length=5), server_default='USD', nullable=True))
        batch_op.create_foreign_key('fk_client_folders_producto_id', 'products', ['producto_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_folders', schema=None) as batch_op:
        batch_op.drop_constraint('fk_client_folders_producto_id', type_='foreignkey')
        batch_op.drop_column('moneda_estimada')
        batch_op.drop_column('valor_estimado')
        batch_op.drop_column('producto_id')
        batch_op.drop_column('estado')

    op.drop_table('client_abonos')
    op.drop_table('products')
    # ### end Alembic commands ###
