"""add quotations module

Revision ID: 5a15fce74aea
Revises: 021886d797e9
Create Date: 2026-06-13 14:36:00.817358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a15fce74aea'
down_revision = '021886d797e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('mensaje_id', sa.Integer(), nullable=True),
    sa.Column('cliente_nombre', sa.String(length=120), nullable=False),
    sa.Column('cliente_empresa', sa.String(length=120), nullable=True),
    sa.Column('cliente_email', sa.String(length=120), nullable=True),
    sa.Column('cliente_telefono', sa.String(length=30), nullable=True),
    sa.Column('cliente_pais', sa.String(length=80), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('moneda', sa.String(length=5), nullable=False),
    sa.Column('incoterm', sa.String(length=20), nullable=True),
    sa.Column('validez_dias', sa.Integer(), nullable=True),
    sa.Column('condiciones', sa.Text(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('descuento_pct', sa.Float(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('fecha_emision', sa.DateTime(), nullable=True),
    sa.Column('fecha_vencimiento', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['folder_id'], ['client_folders.id'], ),
    sa.ForeignKeyConstraint(['mensaje_id'], ['mensajes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero')
    )
    op.create_table('quotation_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    op.drop_table('quotation_lines')
    op.drop_table('quotations')
