"""add leido field to ContactMessage

Revision ID: bb64d40ac679
Revises: 46e63f6077a5
Create Date: 2025-09-13 15:17:51.322772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb64d40ac679'
down_revision = '46e63f6077a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensajes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('leido', sa.Boolean(), nullable=True))
        batch_op.alter_column('fecha',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mensajes', schema=None) as batch_op:
        batch_op.alter_column('fecha',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('leido')

    # ### end Alembic commands ###
